README.md
Some minor copy updates to the readme, trying to make it clear that this is to be used with the App Framework, not node apps in general.
=> docs: readme copy

package.json
We re-export one of the types from the debug module. This meant that people using
node-apps-toolkit would have to add the @types/debug dependency to their project!
=> fix: include @types/debug in dependencies

.commitlintrc.js, .commitlintrc.json
This should work as long as dependabot does not change name or the convention around signed-off commits stays the same
=> chore: exclude dependabot from checked commits

src/keys/get-management-token.spec.ts, src/keys/get-management-token.ts
I'm currently unable to use the cache because I am making requests against multiple spaces.  Not sure if there is a reason `spaceId` wasn't included in the cacheKey but this would solve that issue for me.
=> fix: include spaceId as part of cacheKey

.github/dependabot.yml, package-lock.json, package.json
Semantic release uses node 18
Can be reverted once we use Node 18 in CI
=> chore: downgrade semantic-release

src/requests/typings/deliveryFunction.ts
In the PH on Tuesday we discussed the following changes
* Revert the handler map to a handler function using type unions
* Add a helper to make "type save" event handlers
* Add a `isIntrospectionQuery` boolean to the `graphql.query` event.
* Allow `GraphQLQueryArgument` to be a `Record<string, string>` to allow for multi-argument `GraphQLQueryField` calls. The record key would be the argument name, the key value a JSON Pointer (not set in stone, we might use a different string format) that points to the JSON property that needs to be extracted from the field value and provided as the argument value.
=> feat: update delivery function handler interface

src/index.ts, src/requests/index.ts
We were exporting delivery event as a type and then using it in the template as a value
=> fix: export as value and not type [MONET-1440]

src/requests/typings/appAction.ts
Hosted app actions include a `cmaHost` context value, which is used to instantiate a CMA client in the correct region. The typing for `AppActionCallContext` was not updated at the time, so the value isn't accessible in a type safe manner inside the HAA handler.
* Add the value to the type. It's intentionally not specified as optional, which might be a smarter choice if HAAs had a larger adoption. Since they are internal only for now, I believe it's safe to assume that all HAAs have been updated and do include the `cmaHost`
=> feat: update AppActionCallContext type to reflect cmaHost

src/index.ts, src/requests/index.ts, src/requests/typings/deliveryFunction.ts
This way we can avoid the noise with 
```
const fieldMappingHandler: EventHandler<'graphql.field.mapping'> = (event, context) => {
...
}
```
=> fix: clean up types by avoiding enums [MONET-1476]

package.json
[documentation for this package.json field](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#repository) 
tl;dr: 
> Specify the place where your code lives. This is helpful for people who want to contribute. If the git repo is on GitHub, then the npm docs command will be able to find you.
Without this, the CONTRIBUTING.md link fails when clicked via the npm homepage.
=> fix: set repository url 

README.md
bumping the package version to release previous commits that fixed support for node 18:
- https://github.com/contentful/node-apps-toolkit/pull/368
- https://github.com/contentful/node-apps-toolkit/commit/62a18e071b3a3bbe6ac13300945aec5dc2415dd2
=> fix: explicit support for node 18

src/requests/typings/deliveryFunction.ts
Updates the Delivery Function `GraphQLFieldTypeMapping` type to comply with the changes made in https://github.com/contentful/graph-api/pull/5477
=> feat: make graphQLOutputType optional

package-lock.json, package.json
If we upgrade the app action CMA to https://github.com/contentful/app-upload-to-delivery/pull/269 then the type here https://github.com/contentful/node-apps-toolkit/blob/master/src/requests/typings/appAction.ts#L1 is out of whack with the type provided by the actual app action runtime.
This makes for annoying complaints in typescript, since typescript is aware of the discrepancy between the two different APIs.
=> fix: upgrade to latest contentful-management.js

.circleci/config.yml
semantic-release requires node version >=20.8.1
=> fix: use node 20.8.1 for semantic-release in CICD []

src/requests/typings/function.ts
- All app events now receive `headers` and `body` as input. 
- Transformation functions are now allowed to modify the headers as well as the body of the app event. 
- The entity/action come through via the X-Contentful-Topic header
=> fix: app event function interfaces [EXT-5171]

src/requests/typings/function.ts, src/requests/typings/resources.ts
Function events have been recently extended to support resources events (used in Extensible Resource Links), but all the types are so far only defined locally in `extensible-resource-links-example` example code. We want to unify the function types to cover the new events.
=> feat: add types for resource events [DANTE-1605]

src/requests/typings/function.ts
This PR adds the new `appaction.call` type to be used when creating a function that an app action can target.
=> feat: add appaction.call to types [EXT-5682]

src/requests/typings/appAction.ts, src/requests/typings/function.ts
The body of an App Action Function request will include different properties based on what the Schema of the App Action is. This changeset allows Function developers to optionally specify the Schema of their App Action, giving them better information about what is available in the body of the request. Developers can also optionally provide their own types when using the `Custom` option.
=> feat: better app action function types [EXT-5711]

src/requests/sign-request.spec.ts
adds a quick test to ensure different retries create different signatures. This is already working today and wanted some coverage for the future.
=> test: add retry header test

src/requests/typings/function.ts
We needed to add generics to `FunctionEventHandlers` in order to support someone defining specific types for the `AppActionCategory` and `AppActionRequestBody` when defining a function handler for an `appaction.call`. This will ultimately fix a type error we are seeing in our app action function example.
=> fix: app action request function event handler type [EXT-5710]

src/requests/typings/resources.ts
Align the types of the "resources.search" event to be the same as https://github.com/contentful/functions-api/pull/1177
=> Update types of resources.search event

package.json, src/index.ts, src/requests/index.ts, src/requests/typings/event-payloads.ts, src/requests/typings/function.ts, src/requests/typings/index.ts, src/requests/typings/resources.ts
- each entity/action event payload type is now enumerated explicitly, rather than exposing a single type for each entity across all actions
- exports an enum for App Function event types
=> feat: accurate TS types for each App Event payload type

package-lock.json, src/requests/typings/function.ts
To use the CMA in a function, install `contentful-management` into your project and initialize it like so: 
```typescript
import * as contentful from "contentful-management";
export const handler: FunctionEventHandler<
FunctionTypeEnum.AppEventHandler,
> = async (event: AppEventRequest, context: FunctionEventContext) => {
const cma = contentful.createClient(
context.cmaClientOptions!,
{
defaults: {
spaceId: context.spaceId,
environmentId: context.environmentId,
},
type: "plain",
}
);
// ...
}
=> feat: include cmaClientOptions in FunctionEventContext [EXT-6303]

.github/CODEOWNERS, catalog-info.yaml
We recently renamed our team in work day and that finally synced in github.
team-tundra -> team-extensibility
=> fix: rename team-tundra -> team-extensibility [EXT-6372]

CHANGELOG.md
We recently renamed our team in work day and that finally synced in github.
team-tundra -> team-extensibility
=> chore: fix changelog [EXT-6372]
